# Generated by Django 5.2.5 on 2025-08-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_options_menu_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order for drag and drop functionality'),
        ),
    ]
