# Generated by Django 5.2.5 on 2025-08-08 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'id']},
        ),
    ]
