# Generated by Django 5.2 on 2025-08-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
        migrations.AlterField(
            model_name='menu',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
