# Generated by Django 5.2.5 on 2025-08-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menu_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-order', 'id']},
        ),
    ]
